version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGH_Exp1108Project
  gitServerName: srcGithubCtrl_Arti_exp1108
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
