version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGH_Exp1108Project
  gitServerName: srcGithubCtrl_Arti_exp1108
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: DivisionPackage
  version: "5.0"
  gitServerName: src_shared_GithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: second_branch
services:
- serviceName: project.serengetigh_exp1108.integrations:gcd1108
  packages:
  - name: SerengetiGH_Exp1108Project
    version: "1.0"
  - name: DivisionPackage
    version: "5.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.1032
- serviceName: project.serengetigh_exp1108.integrations:githubfs
  packages:
  - name: SerengetiGH_Exp1108Project
    version: "1.0"
  - name: DivisionPackage
    version: "5.0"
- serviceName: DivisionPackage:division_service
  packages:
  - name: DivisionPackage
    version: "5.0"
- serviceName: pub.math:divideInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1032
- serviceName: project.serengetigh_exp1108.integrations:ll
  packages:
  - name: SerengetiGH_Exp1108Project
    version: "1.0"
  - name: DivisionPackage
    version: "5.0"
- serviceName: pub.string:toLower
  packages:
  - name: WmPublic
    version: 12.1.0.0.1032
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
